version: '3'
services:
  backend-for-frontend:
    build:
      context: .
      dockerfile: frontend/docker/development/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    stdin_open: true
    tty: true
    command: ["pnpm", "dev", "-o"]
  api-server:
    build:
      context: .
      dockerfile: ./backend/docker/development/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app/backend
    stdin_open: true
    tty: true
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]