name: Deploy to Google Cloud Run - Staging

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - release-*
  workflow_dispatch:

jobs:
  vitest:
    name: Run Vitest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and run tests
        run: |
          npm install -g pnpm
          pnpm install
          pnpm test:vitest
        working-directory: ./frontend

  playwright:
    name: Run Playwright Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies and run Playwright tests
        run: |
          pnpm install
          pnpm playwright install --with-deps
          pnpm test:e2e
        working-directory: ./frontend
        env:
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_API_ENDPOINT: ${{ secrets.RAKUTEN_API_ENDPOINT }}
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./tests/e2e/pages/screenshots/${{ github.ref_name }}

      - name: Upload screenshots to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: frontend/tests/e2e/pages/screenshots/${{ github.ref_name }}
          destination: webtech-bookstore/${{ github.ref_name }}/
          credentials: ${{ secrets.GCP_SA_KEY }}
          parent: false

  build-and-deploy:
    name: Build and Deploy
    needs: [vitest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build --build-arg RAKUTEN_APP_ID=${{ secrets.RAKUTEN_APP_ID }} \
          --build-arg RAKUTEN_API_ENDPOINT=${{ secrets.RAKUTEN_API_ENDPOINT }} \
          --build-arg MODE=stage \
          -f frontend/docker/production/Dockerfile \
          -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/webtech-bookstore-bff:${{ github.sha }} frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/webtech-bookstore-bff:${{ github.sha }}

      - name: Deploy to Google Cloud Run - Staging
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          IMAGE="gcr.io/${{ secrets.GCP_PROJECT_ID }}/webtech-bookstore-bff:${{ github.sha }}"

          if [ -z "$PR_NUMBER" ]; then
            # プルリクエスト番号がない場合、タグなしでデプロイ
            gcloud run deploy webtech-bookstore-bff-stage \
              --image $IMAGE \
              --platform managed \
              --region asia-northeast1 \
              --allow-unauthenticated
          else
            # プルリクエスト番号がある場合、タグ付きでデプロイ
            TAG="pr-${PR_NUMBER}"
            gcloud run deploy webtech-bookstore-bff-stage \
              --image $IMAGE \
              --tag $TAG \
              --platform managed \
              --region asia-northeast1 \
              --allow-unauthenticated
          fi